# Generated by Django 4.2.1 on 2023-05-29 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-created'], 'verbose_name': 'servicio', 'verbose_name_plural': 'servicios'},
        ),
        migrations.RenameField(
            model_name='service',
            old_name='update',
            new_name='updated',
        ),
    ]
